* <2025-04-09 Wed> GE                                                :frågor:

1. Behöver det färdiga lexikonet verkligen passera genom transtool och
   därmmed vara beroende av de begränsningar som ordbasen där ger? Eller
   kan man kanske helt enkelt bara köra in det som finns i indata?
  Förmodligen inte ...

2. Vad händer om sv-material i indata inte (helt) överensstämmer med
   ordbasen? Finns ddet nåt sätt attt få med översättningarna ändå
   eller är sådant material bara att dumpa? Det kan gälla:
   - definition
   - sammansätttning
   - exempel
   - idiom
   - annat?
     
* <2025-04-17 Thu> GE
Lite kollar på täckningen för aktuell lexin sv-uppslag (unnder S) i
kelderashdaata:

#+begin_src bash
time grep '#01' s.txt | cut -f2- -d' ' | sed 's/\~//g' | raku api2.raku --status | grep '"Wordbase"' | sunis
#+end_src

: 1563       "Wordbase": "LSL4",
: 1439       "Wordbase": "LSL4"
: 
: real	2m12.952s
: user	0m57.943s
: sys 	0m4.713s

#+begin_src bash
time grep '#01' s.txt | cut -f2- -d' ' | sed 's/\~//g' | raku api2.raku --status > status_S.json
#+end_src

: real	2m16.439s
: user	0m58.635s
: sys 	0m4.699s

#+begin_src bash
grep '#01' s.txt | wc -l
#+end_src

:    3039

#+begin_src bash
grep '"Status"' status_S.json | sunis
#+end_src

: 1389       "Status": "found"
: 1369       "Status": "found",
:  147       "Status": "no unique matching",
:   52       "Status": "no unique matching"
:   37       "Status": "no matching"
:   31       "Status": "corrected",
:   14       "Status": "corrected"

<2025-04-26 Sat>
(Förhoppningsvis) samma körningssresultat med ny form för indata:

#+begin_src bash
   time cat ../kelderasch_filer/s.json | raku -MJSON::Fast -e '$*IN.slurp.&from-json.map: *.<#01>.subst("~", "|",:g).say' | raku api2.raku --status > status_swe-swe_S.json 
#+end_src

<2025-04-29 Tue>

Också för swe_fin (dvs. "Wordbase": "LSL3"):
#+begin_src bash
  time cat ../kelderasch_filer/s.json | raku -MJSON::Fast -e '$*IN.slurp.&from-json.map: *.<#01>.subst("~", "|",:g).say' | raku api2.raku --lang='swe>fin' --status > status_swe-fin_S.json 
#+end_src

Med statistik (för S):
#+begin_src bash
  cat  status_swe-fin_S.json | grep Status | raku -ne 'say .subst(/","\h*$/, "")' | sunis

  cat  status_swe-fin_S.json | grep ':' | raku -ne 'say .subst(/","\h*$/, "")' | sunis
#+end_src

: 2196       "Status": "found"
:  662       "Status": "corrected"
:  172       "Status": "no unique matching"
:    9       "Status": "no matching"

: 3030       "Wordbase": "LSL3"
: 2196       "Status": "found"
:  662       "Status": "corrected"
:  172       "Status": "no unique matching"
:    9       "Status": "no matching"

swe_swe (igen):
: 2994       "Wordbase": "LSL4"
: 2162       "Status": "found"
:  832       "Corrections": [
:  632       "Status": "corrected"
:  200       "Status": "no unique matching"
:   45       "Status": "no matching"

: 2162       "Status": "found"
:  632       "Status": "corrected"
:  200       "Status": "no unique matching"
:   45       "Status": "no matching"

* <2025-04-29 Tue>╭                                              :viggo_json:
Jag hade problem med att få körning mot =LSL3= dvs. =swe_fin= att gå
igenom. Efter ganska mycket letande hittade jag det i brister i den
json som produceras av lexins (json)-API.

Enda fallet (under boksatven S) som ställer till problem är:
#+begin_src
"Value": "omv\u00e4nt snedstreck",
"Type": "subst.",
"VariantID": "12445",
[ ... ]
"Meaning": "tecknet \", 
#+end_src

där alltså sekvensen '\"' är ett specialtecken för inbäddade
dubbelfnuttar och vad saknas för att få giltig json är escapning av
'\': 
#+begin_src 
"Meaning": "tecknet \\", 
#+end_src

Jag har löst det temporärt genom att skriva om just den strängen till
den escapade motsvarigheten, men ska kontakta Viggo i ärendet,
fler kan ju få problem, exempelvis =lexin.se= som vad jag förstår
använder json-apiet ....

* <2025-05-07 Wed>
Jag hittar allt fler fall där sökningar på det svenska uppslaget inte
ger det svar (beträffande ID och VariantID) som på nåt
tillfredställande sätt motsvarar informationen i
kelderashmaterialet. I vissa fall ID-värdena överenstämma men den
svenska diefinitionen eller nåt (svenskt) exempel skiljer sig åt. Även
då är det svårt att mappa samman dem ... Eller?

Jag borde sammanställa en liten hög med enxempel.

Jag kollade också lite på hur många oöversatta poster det finns i
materialet:

#+begin_src bash
cat ../kelderasch_filer/s.json | raku -MJSON::Fast -e 'for $*IN.slurp.&from-json { next if .<#31>; next if .<#02> ~~ /^"se "/; next if .<#54>; say .<#01> }' | wc -l
     156
#+end_src

#+begin_src bash
for f in  ../kelderasch_filer/*.json; do  cat $f | raku -MJSON::Fast -e 'for $*IN.slurp.&from-json { next if .<#31>; next if .<#02> ~~ /^"se "/; next if .<#54>; say .<#01> }'; done | wc -l
   2407
#+end_src

* <2025-05-14 Wed> GE                                                 :Viggo:

Viggo berättade att haan redan gjort en parser för "radformatet" och
producerat en xmlfil. Dock hittade han då ett antal fel i indata:

- en lista med "felstavningar"
- c:a 300 ord som bara saknas.

de saknade orden:
| löpnr | swe_fin                                                                                                |
|-------+--------------------------------------------------------------------------------------------------------|
| 16320 | <Word ID="14758" MatchingID="18880" Type="subst." Value="slipover" Variant="" VariantID="16320">       |
| 16321 | <saknas> <Word ID="14759" MatchingID="18881" Type="verb" Value="slipper" Variant="" VariantID="16321"> |
|   ... | <flera saknade ord>                                                                                    |
| 16686 | <saknas> <Word ID="15093" MatchingID="19301" Type="subst." Value="snus" Variant="" VariantID="16686">  |
| 16687 | <Word ID="15094" MatchingID="19302" Type="verb" Value="snusar" Variant="" VariantID="16687">           |

#+begin_src emacs-lisp
(- 16687 16320)
#+end_src

#+RESULTS:
: 367

Alltså 367 ord.

* <2025-05-15 Thu> GE
Jag har diffat lite impressionistiskt på Viggos fil
=lexinextra/dictionaries/swe_kal.txt= och våra/Bakis filer och tycker
mig se skilllnader åt båda håll. Alltså "våra" verkar bättre/nyare
ibland och ibland tvärtom. Vi behöver nog få (nån slags uppskattning
om) redigeringsdatum av både Baki och Viggo.

Om vi i slutändan ska göra nån slags egen diff på avsiktliga och
ovsiktliga skillnder måste visortera materialet ett sätt som
överensstämmer med Viggos sorteringsordning. Det borde ju vara en
trivial sak via unicodes =colllation order=, men det klarar varken
python (säger Magnus) eller raku (vet jag av egen bister
erfarenhet). Så nu började jag skissa på en rudimentär och pinsamt
förskoleliknade lösning:

#+begin_src raku
  my %swe is default(29) = <å 30 ä 31 ö 32>;
  sub swe ($a, $b) {
   if $a, $b ⊂ %swe.keys { # delmängd är förstås fel!
       %swe{$a.lc} cmp %swe{$b.lc} 
   } else { $a coll $b }
  } 


#+end_src

Nja,ovanstående funkar fast på fel grunder:
#+begin_src 
[16] > swe "Z","Ä"
Less
[17] > swe "B","b"
Same
[18] > swe "Ö","b"
More
[19] > swe "Ö","ä"
More
[20] > swe "å","ä"
Less
[21] > swe "Å","Ä"
Less
[22] > swe "Ä","Å"
More
[23] > %swe<A>
29
[24] > %swe<Ö>
29
[25] > %swe<ö>
32
[26] > <Ö A> (<) %swe.keys 
False
[27] > <ö a> (<) %swe.keys 
False
[28] > %swe.keys 
(ö ä å)
[29] > <ö a> (<) <a b c>
False
[30] > <ö ä> (<) <a b c>
False
[31] > <ö ä> (<) <a b c>.Set
False
[32] > <ö ä> (<) <a b c ö ä>
True
[33] > <ö ä> (<) <a b c ö>
False
[34] > <ö ä>.collate
(ä ö)
[35] > <ö ä å>.collate
(å ä ö)
[36] > <Å o O a ö ä m Ö n g å>.collate
(a å Å ä g m n o O ö Ö)
[37] > <ö ä å>.sort
(ä å ö)
[38] > 

#+end_src

#+begin_src raku :results output 
      sub swe ($a, $b) {
          my @in = ($a, $b)».lc; 
          my $swe = <å ä>.Set; 
          #say @in ~~ $swe; 
          

      #    given ($a, $b)».lc {
      #        when * ⊂ $swe and{ say "swe: "  }
      #        default { say "coll"  }
      #    }
    }

  swe "Ä", "Ä"; 
#+end_src 

#+RESULTS:
: False

#+begin_src raku :results output 
  subset Å   of Str where * ∈ <å Å>; 
  subset Ä   of Str where * ∈ <ä Ä>; 
  subset nÅÄ of Str where * ∉ <ä Ä å Å>; 

  multi swe (Å $a, Ä $b) { note 111; Less }
  multi swe (Ä $a, Å $b) { note 222; More }
  multi swe ($a, nÅÄ $b) { note 333; $a coll $b }
  multi swe (nÅÄ $a, $b) { note 444; $a coll $b }




       #my @in = ($a, $b)».lc; 
            #my $swe = <å ä>.Set; 
            #say @in ~~ $swe; 


        #    given ($a, $b)».lc {
        #        when * ⊂ $swe and{ say "swe: "  }
        #        default { say "coll"  }
        #    }
      #}

  say swe "ä", "å"; 
  say "ä" coll "å"; 

  say swe "ö", "o"; 
  say "ö" coll "o"; 
#+end_src 

#+RESULTS:
: More
: More
: More
: More

* <2025-05-28 Wed> GE                                                 :Viggo:
Lite mer konversation med Viggo:

* <2025-06-12 Thu>
småstartat diffning genmot Viggos sww_kal.txt:
#+begin_src bash
swe_kal.txt | head -100 | raku -e '$*IN.slurp.split(/^^[\h*\n]+/).map: { my %h = do for .split(/\h*\n\h*/, :skip-empty) -> $r {  my ($k, $v) = $r.split: /\h+/, 2; $k => $v }; dd %h}'
#+end_src


* <2025-06-25 Wed>
Viggo:

Här är den beskrivning av formatet som jag hittade. Förmodligen används inte alla koder i det aktuella lexikonet.
| #01 | uppslagsord, ev. följt av nummer (= xxx)                       |
| #02 | ordklassbeteckning                                             |
| #04 | ordförklaring                                                  |
| #05 | stilkommentar                                                  |
| #06 | sakupplysning                                                  |
| #07 | satsexempel; löpnummer i 47                                    |
| #08 | idiomexempel; löpnummer i 48                                   |
| #09 | referens till bild eller annat uttryck                         |
| #10 | syntaxmarkering, t ex "x & y"                                  |
| #11 | sammansättningsexempel; löpnummer i 51                         |
| #12 | ordböjning, hela ord eller inlett med "-" om 10 innehåller "~" |
| #13 | stavningsvariant                                               |
| #14 | uttal                                                          |
| #15 | grammatikkommentar                                             |
| #31 | övers. av #01                                                  |
| #32 | övers. av #02                                                  |
| #35 | övers. av #05                                                  |
| #36 | övers. av #06                                                  |
| #37 | övers. av #07                                                  |
| #38 | övers. av #08                                                  |
| #39 | övers. av #09                                                  |
| #41 | övers. av #11                                                  |
| #45 | övers. av #15                                                  |
| #54 | övers. av #04                                                  |
| #47 | löpnummer för exempel                                          |
| #48 | löpnummer för idiom                                            |
| #51 | löpnummer för sammansättning                                   |
| #98 | löpnummer för olika uppslagsord                                |
| #99 | löpnummer för uppslagsord (inkl varianter)                     |
 

Fortsaatt och committat viggoprepareringen i
=viggo-swe_kal2json.raku=. Men sammtidigt hittat strukturproblem: en
del enklaare är jag ändrat för hand i =swe_kal-red.txt=. Andra är
svårare: multipla källfält med motsv överssättningsfält. Problemen är
gemensamma för Baki- och Viggomaterialen:

#+begin_src json
    "#01": "övning",
    "#31": "zumavel",
    "#02": "subst.",
    "#32": "substantivo",
    "#04": "det att öva, träning",
    "#05": "även om den uppgift som övas",
    "#35": "",
    "#07": "övning ger färdighet",
    "#37": "",
    "#47": "12459",
    "#11": "övnings~uppgift  en",
    "#41": "",
    "#51": "8136",
    "#12": "övningen övningar",
    "#14": "2Ö:vni@",
    "#98": "19706",
    "#99": "21876",
    "#54": "zumavel",
    "#97": "mini"
  },
#+end_src

#+begin_example
#01 övning
#31 zumavel
#02 subst.
#32 substantivo
#04 det att öva, träning
#05 även om den uppgift som övas
#35 
#07 övning ger färdighet
#37 
#47 12459
#11 skrivövning
#41 
#51 8134
#11 militärövning
#41 
#51 8135
#11 övnings~uppgift  en
#41 
#51 8136
#12 övningen övningar
#14 2Ö:vni@
#98 19706
#99 21876
#54 zumavel
#97 mini
#+end_example
